build:
  maxIssues: 200

style:
  MaxLineLength:
    active: true
    maxLineLength: 140
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    max: 10
  ThrowsCount:
    active: true
    max: 10
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 10

complexity:
  active: true
  LargeClass:
    active: false
  LongMethod:
    active: true
    threshold: 200
  ComplexCondition:
    active: true
    threshold: 10
  NestedBlockDepth:
    active: true
    threshold: 20
  LongParameterList:
    active: true
    functionThreshold: 20
    constructorThreshold: 20
  CyclomaticComplexMethod:
    active: true
    threshold: 200
  TooManyFunctions:
    active: true
    thresholdInFiles: 50
    thresholdInClasses: 50
    thresholdInInterfaces: 50
    thresholdInObjects: 50
    thresholdInEnums: 50
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false
